@BASE_URL=http://localhost:3000/graphql
@TOKEN=<TOKEN>

### Users Query
# This should be Admin only
POST {{BASE_URL}}
Content-Type: application/json
Authorization: Bearer {{TOKEN}}
X-REQUEST-TYPE: GraphQL

query {
  users {
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
    edges {
      node {
        id
        name
        email
        createdAt
        updatedAt
      }
    }
  }
}
