@BASE_URL=http://localhost:3000/graphql
@TOKEN=<TOKEN>

### Users Query
# This should be Admin only
POST {{BASE_URL}}
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "query": "query { users { id name email } }"
}
